// StingBIM.AI.Collaboration.LAN.BEPGenerator
// ISO 19650 BIM Execution Plan generator — 14 sections
// v4 Prompt Reference: Section C.3 — BIM Execution Plan Generator

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Autodesk.Revit.DB;
using Newtonsoft.Json;
using NLog;

namespace StingBIM.AI.Collaboration.LAN
{
    /// <summary>
    /// Generates a complete BIM Execution Plan (BEP) compliant with ISO 19650.
    /// Produces a structured text document with 14 sections covering:
    /// project info, BIM goals, team, software, naming, LOIN, coordinates,
    /// model breakdown, information exchange, CDE, QA, deliverables,
    /// federated model management, and security.
    /// </summary>
    public class BEPGenerator
    {
        private static readonly ILogger Logger = LogManager.GetCurrentClassLogger();

        /// <summary>
        /// Generate a full BEP from the project document and team data.
        /// </summary>
        public BEPResult Generate(Document doc, string serverPath, string projectName)
        {
            Logger.Info($"Generating BEP for: {projectName}");

            try
            {
                var teamFile = Path.Combine(serverPath, $"{projectName}_team.json");
                var team = new List<TeamMember>();
                if (File.Exists(teamFile))
                {
                    var json = File.ReadAllText(teamFile);
                    team = JsonConvert.DeserializeObject<List<TeamMember>>(json) ?? new List<TeamMember>();
                }

                var sb = new StringBuilder();

                // Title page
                sb.AppendLine("═══════════════════════════════════════════════════════════════");
                sb.AppendLine("               BIM EXECUTION PLAN (BEP)");
                sb.AppendLine("               ISO 19650 Compliant");
                sb.AppendLine("═══════════════════════════════════════════════════════════════");
                sb.AppendLine();

                // Section 1: Project Information
                GenerateSection1_ProjectInfo(sb, doc, projectName);

                // Section 2: BIM Goals & Use Cases
                GenerateSection2_BIMGoals(sb);

                // Section 3: Project Team & Responsibilities
                GenerateSection3_Team(sb, team);

                // Section 4: Software & Standards
                GenerateSection4_Software(sb);

                // Section 5: Naming Conventions
                GenerateSection5_Naming(sb, projectName);

                // Section 6: Level of Information Need (LOIN)
                GenerateSection6_LOIN(sb);

                // Section 7: Coordinate System
                GenerateSection7_Coordinates(sb, doc);

                // Section 8: Model Breakdown Structure
                GenerateSection8_ModelBreakdown(sb);

                // Section 9: Information Exchange Requirements
                GenerateSection9_InformationExchange(sb);

                // Section 10: Common Data Environment (CDE)
                GenerateSection10_CDE(sb, serverPath);

                // Section 11: Quality Assurance
                GenerateSection11_QA(sb);

                // Section 12: Deliverables Schedule
                GenerateSection12_Deliverables(sb);

                // Section 13: Federated Model Management
                GenerateSection13_FederatedModel(sb, serverPath);

                // Section 14: Security
                GenerateSection14_Security(sb);

                // Footer
                sb.AppendLine();
                sb.AppendLine("═══════════════════════════════════════════════════════════════");
                sb.AppendLine($"Generated by StingBIM v7 — {DateTime.Now:yyyy-MM-dd HH:mm}");
                sb.AppendLine("═══════════════════════════════════════════════════════════════");

                var content = sb.ToString();

                // Save to server
                var outputPath = Path.Combine(serverPath, $"{projectName}_BEP.txt");
                File.WriteAllText(outputPath, content);

                Logger.Info($"BEP generated: {outputPath}");

                return new BEPResult
                {
                    Success = true,
                    FilePath = outputPath,
                    Content = content,
                    SectionCount = 14,
                    Message = $"BIM Execution Plan generated with 14 sections.\nSaved to: {outputPath}"
                };
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "BEP generation failed");
                return new BEPResult
                {
                    Success = false,
                    Message = $"BEP generation failed: {ex.Message}"
                };
            }
        }

        #region BEP Sections

        private void GenerateSection1_ProjectInfo(StringBuilder sb, Document doc, string projectName)
        {
            sb.AppendLine("1. PROJECT INFORMATION");
            sb.AppendLine("───────────────────────────────────────────────────────────────");

            var projInfo = doc.ProjectInformation;
            sb.AppendLine($"  Project Name:     {projInfo?.Name ?? projectName}");
            sb.AppendLine($"  Project Number:   {projInfo?.Number ?? "TBD"}");
            sb.AppendLine($"  Client:           {projInfo?.ClientName ?? "TBD"}");
            sb.AppendLine($"  Address:          {projInfo?.Address ?? "TBD"}");
            sb.AppendLine($"  Issue Date:       {DateTime.Now:yyyy-MM-dd}");
            sb.AppendLine($"  BEP Revision:     1.0");
            sb.AppendLine($"  Status:           For Information");
            sb.AppendLine($"  Building Type:    {projInfo?.BuildingName ?? "TBD"}");
            sb.AppendLine();
        }

        private void GenerateSection2_BIMGoals(StringBuilder sb)
        {
            sb.AppendLine("2. BIM GOALS & USE CASES");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  BIM Use Cases:");
            sb.AppendLine("  [x] Design Authoring — 3D parametric modelling in Revit");
            sb.AppendLine("  [x] Design Reviews — Coordination reviews with stakeholders");
            sb.AppendLine("  [x] 3D Coordination — Clash detection between disciplines");
            sb.AppendLine("  [x] Cost Estimation — BOQ and quantity takeoff");
            sb.AppendLine("  [x] Construction Planning — 4D sequencing");
            sb.AppendLine("  [x] Facility Management Handover — COBie data export");
            sb.AppendLine();
            sb.AppendLine("  BIM Goals:");
            sb.AppendLine("  - Reduce design clashes by 80% before construction");
            sb.AppendLine("  - Achieve ISO 19650 compliance for information management");
            sb.AppendLine("  - Deliver accurate quantities for procurement");
            sb.AppendLine("  - Enable seamless FM handover with complete asset data");
            sb.AppendLine();
        }

        private void GenerateSection3_Team(StringBuilder sb, List<TeamMember> team)
        {
            sb.AppendLine("3. PROJECT TEAM & RESPONSIBILITIES (ISO 19650 Roles)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("  Role                          | Name            | Organisation");
            sb.AppendLine("  ─────────────────────────────|─────────────────|──────────────");
            sb.AppendLine("  Information Manager           | TBD             | Client");
            sb.AppendLine("  Lead Appointed Party          | TBD             | Lead Consultant");

            foreach (var member in team)
            {
                sb.AppendLine($"  Appointed Party               | {member.UserName,-15} | {member.MachineName}");
            }

            if (team.Count == 0)
            {
                sb.AppendLine("  Appointed Party               | (none yet)      | -");
            }

            sb.AppendLine();
            sb.AppendLine("  Active Team Members:");
            foreach (var member in team)
            {
                var syncInfo = member.LastSync > DateTime.MinValue
                    ? $"Last sync: {member.LastSync:yyyy-MM-dd HH:mm}"
                    : "Not yet synced";
                sb.AppendLine($"  - {member.UserName} ({member.MachineName}) — {syncInfo}");
            }
            sb.AppendLine();
        }

        private void GenerateSection4_Software(StringBuilder sb)
        {
            sb.AppendLine("4. SOFTWARE & STANDARDS");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  Platform:         Autodesk Revit 2025 + StingBIM v7");
            sb.AppendLine("  File Format:      .rvt (native), IFC 4 (exchange), DWG (2D)");
            sb.AppendLine("  Standards:");
            sb.AppendLine("    - ISO 19650-1:2018 — Information management principles");
            sb.AppendLine("    - ISO 19650-2:2018 — Delivery phase");
            sb.AppendLine("    - ISO 19650-5:2020 — Security-minded approach");
            sb.AppendLine("    - Uganda Building Control Act 2013");
            sb.AppendLine("    - UNBS US 319:2003 — Building Code");
            sb.AppendLine("    - BS EN 1990-1999 (Eurocodes via EAS adoption)");
            sb.AppendLine();
        }

        private void GenerateSection5_Naming(StringBuilder sb, string projectName)
        {
            var code = projectName.Length >= 7
                ? projectName.Substring(0, 7).ToUpper()
                : projectName.ToUpper().PadRight(7, 'X');

            sb.AppendLine("5. NAMING CONVENTIONS (ISO 19650)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  Document Naming Pattern:");
            sb.AppendLine("    [Project]-[Originator]-[Volume]-[Level]-[Type]-[Role]-[Number]");
            sb.AppendLine();
            sb.AppendLine($"    Example: {code}-SBM-ZZ-XX-M3-AR-0001");
            sb.AppendLine();
            sb.AppendLine("  Field Definitions:");
            sb.AppendLine($"    Project:     {code}");
            sb.AppendLine("    Originator:  SBM (StingBIM)");
            sb.AppendLine("    Volume:      ZZ (all volumes) / 01, 02...");
            sb.AppendLine("    Level:       XX (all levels) / 00, 01, 02...");
            sb.AppendLine("    Type:        M3 (3D model), DR (drawing), SH (schedule)");
            sb.AppendLine("    Role:        AR (Architecture), ST (Structure),");
            sb.AppendLine("                 ME (Mech), EL (Electrical), PL (Plumbing)");
            sb.AppendLine("    Number:      0001, 0002... sequential");
            sb.AppendLine();
        }

        private void GenerateSection6_LOIN(StringBuilder sb)
        {
            sb.AppendLine("6. LEVEL OF INFORMATION NEED (LOIN)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  (Replaces traditional LOD/LOI distinction per ISO 19650)");
            sb.AppendLine();
            sb.AppendLine("  Stage            | RIBA  | Geometry Detail     | Information Detail");
            sb.AppendLine("  ─────────────────|───────|─────────────────────|───────────────────");
            sb.AppendLine("  Concept          | 1-2   | Indicative volumes  | Purpose, use");
            sb.AppendLine("  Developed Design | 3     | Approximate sizes   | Key performance specs");
            sb.AppendLine("  Technical Design | 4     | Accurate geometry   | Full specifications");
            sb.AppendLine("  Construction     | 5     | Fabrication detail  | Installation data");
            sb.AppendLine("  Handover         | 6     | As-built verified   | Maintenance + O&M data");
            sb.AppendLine();
        }

        private void GenerateSection7_Coordinates(StringBuilder sb, Document doc)
        {
            sb.AppendLine("7. COORDINATE SYSTEM");
            sb.AppendLine("───────────────────────────────────────────────────────────────");

            try
            {
                var basePoint = new FilteredElementCollector(doc)
                    .OfCategory(BuiltInCategory.OST_ProjectBasePoint)
                    .FirstOrDefault();

                var surveyPoint = new FilteredElementCollector(doc)
                    .OfCategory(BuiltInCategory.OST_SharedBasePoint)
                    .FirstOrDefault();

                sb.AppendLine($"  Project Base Point: {(basePoint != null ? "Set" : "Default")}");
                sb.AppendLine($"  Survey Point:       {(surveyPoint != null ? "Set" : "Default")}");
            }
            catch
            {
                sb.AppendLine("  Project Base Point: Default");
                sb.AppendLine("  Survey Point:       Default");
            }

            sb.AppendLine("  True North:         0° (to be set during survey)");
            sb.AppendLine("  Units:              Metric (mm)");
            sb.AppendLine();
        }

        private void GenerateSection8_ModelBreakdown(StringBuilder sb)
        {
            sb.AppendLine("8. MODEL BREAKDOWN STRUCTURE (MBS)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  Federation Strategy:");
            sb.AppendLine("  - Single federated model (workshared)");
            sb.AppendLine("  - Discipline separation via worksets");
            sb.AppendLine();
            sb.AppendLine("  Worksets:");
            sb.AppendLine("  1. Shared Levels & Grids");
            sb.AppendLine("  2. Architecture");
            sb.AppendLine("  3. Structure");
            sb.AppendLine("  4. MEP - Electrical");
            sb.AppendLine("  5. MEP - Plumbing");
            sb.AppendLine("  6. MEP - HVAC");
            sb.AppendLine("  7. MEP - Fire Protection");
            sb.AppendLine("  8. Interior Finishes");
            sb.AppendLine("  9. Site & Landscape");
            sb.AppendLine("  10. Furniture & Equipment");
            sb.AppendLine();
        }

        private void GenerateSection9_InformationExchange(StringBuilder sb)
        {
            sb.AppendLine("9. INFORMATION EXCHANGE REQUIREMENTS (IER)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("  Stage              | Deliverable            | Format | To");
            sb.AppendLine("  ───────────────────|────────────────────────|────────|──────────");
            sb.AppendLine("  Concept            | Massing model          | .rvt   | Client");
            sb.AppendLine("  Developed Design   | Coordinated model      | .rvt   | QS, Eng");
            sb.AppendLine("  Technical Design   | Construction model     | IFC 4  | Contractor");
            sb.AppendLine("  Construction       | As-built model         | .rvt   | FM");
            sb.AppendLine("  Handover           | FM data (COBie)        | .xlsx  | Owner/FM");
            sb.AppendLine();
        }

        private void GenerateSection10_CDE(StringBuilder sb, string serverPath)
        {
            sb.AppendLine("10. COMMON DATA ENVIRONMENT (CDE)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  CDE Type:      Local LAN (offline — no cloud dependency)");
            sb.AppendLine($"  Server Path:   {serverPath}");
            sb.AppendLine();
            sb.AppendLine("  Status Codes:");
            sb.AppendLine("    S0 — Work in Progress");
            sb.AppendLine("    S1 — Suitable for Information");
            sb.AppendLine("    S2 — Suitable for Review");
            sb.AppendLine("    S3 — Suitable for Construction");
            sb.AppendLine("    S4 — As-Built / For Archive");
            sb.AppendLine();
            sb.AppendLine("  Folder Structure:");
            sb.AppendLine($"    {serverPath}");
            sb.AppendLine("    ├── WIP/           (Work in Progress — S0)");
            sb.AppendLine("    ├── Shared/        (Shared — S1/S2)");
            sb.AppendLine("    ├── Published/     (Published — S3)");
            sb.AppendLine("    ├── Archived/      (Archive — S4)");
            sb.AppendLine("    └── _Backup/       (Auto-backups)");
            sb.AppendLine();
        }

        private void GenerateSection11_QA(StringBuilder sb)
        {
            sb.AppendLine("11. QUALITY ASSURANCE");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  QA Checks (performed before each milestone delivery):");
            sb.AppendLine("    1. Visual review — walkthrough in 3D view");
            sb.AppendLine("    2. Automated clash detection — StingBIM coordination check");
            sb.AppendLine("    3. Parameter completeness — all required parameters populated");
            sb.AppendLine("    4. Naming compliance — ISO 19650 naming verified");
            sb.AppendLine("    5. Standards compliance — building code checks");
            sb.AppendLine("    6. Model health — file size, unused families, workset assignment");
            sb.AppendLine();
        }

        private void GenerateSection12_Deliverables(StringBuilder sb)
        {
            sb.AppendLine("12. DELIVERABLES SCHEDULE");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  Milestone deliverables to be confirmed with client.");
            sb.AppendLine("  Typical deliverables per stage:");
            sb.AppendLine("    Concept:      Massing model, area schedule, site plan");
            sb.AppendLine("    Developed:    Coordinated model, door/window schedules, BOQ");
            sb.AppendLine("    Technical:    Construction drawings, specifications, M&E model");
            sb.AppendLine("    Construction: Shop drawings, RFI responses, as-built updates");
            sb.AppendLine("    Handover:     As-built model, O&M manuals, COBie data");
            sb.AppendLine();
        }

        private void GenerateSection13_FederatedModel(StringBuilder sb, string serverPath)
        {
            sb.AppendLine("13. FEDERATED MODEL MANAGEMENT");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  Sync Schedule:     Every 30 minutes (auto-sync)");
            sb.AppendLine($"  Central Model:     {serverPath}\\[Project]_Central.rvt");
            sb.AppendLine("  Backup Schedule:   Every 2 hours (auto-backup)");
            sb.AppendLine("  Backup Retention:  Last 10 backups");
            sb.AppendLine("  Conflict Policy:   Pause auto-sync, alert user, resolve before sync");
            sb.AppendLine("  Lock Policy:       Lock file during sync, auto-cleanup on completion");
            sb.AppendLine();
        }

        private void GenerateSection14_Security(StringBuilder sb)
        {
            sb.AppendLine("14. SECURITY (ISO 19650-5)");
            sb.AppendLine("───────────────────────────────────────────────────────────────");
            sb.AppendLine("  Access Control:");
            sb.AppendLine("    - LAN access restricted to authorized team members");
            sb.AppendLine("    - Workset permissions per discipline");
            sb.AppendLine("    - No external cloud storage of model data");
            sb.AppendLine();
            sb.AppendLine("  Data Sensitivity:");
            sb.AppendLine("    - Project data classified as CONFIDENTIAL");
            sb.AppendLine("    - No model data to leave the LAN without authorization");
            sb.AppendLine("    - USB/external drive policy to be defined by client");
            sb.AppendLine();
        }

        #endregion
    }

    #region BEP Result

    public class BEPResult
    {
        public bool Success { get; set; }
        public string FilePath { get; set; }
        public string Content { get; set; }
        public int SectionCount { get; set; }
        public string Message { get; set; }
    }

    #endregion
}
